name: Build and publish
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Publish as package
        run: npm ci && npm run build && npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
